version: "3"
services:
  docker5_unicom:
    container_name: docker5_unicom
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/AutoSignMachine/scripts/config #同步脚本地址
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: docker5_unicom
    environment:
      - enable_unicom=true

