name: "Asm-wrapper Docker Image Buildx Stable Github"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Asm-wrapper Docker Image Build Stable Github
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: xclamp/asm-wrapper
          dockerFile: docker/Dockerfile_unicom
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: unicom
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
